config/routes.rb
Points::Application.routes.draw do

    resources :activities  
    resources :actions
    resources :txns
   

   root :to => "txns#new"
   match "/" => "txns#new"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  default_scope :order => "title"

  has_many :actions

end

app/models/txn.rb
class Txn < ActiveRecord::Base
  default_scope :order => "id"
  belongs_to :activity

  def self.total_points txn_date
    # Txn.sum(:points, :conditions => ["txn_date >= ? AND txn_date < ?", txn_date, (txn_date + 1.days)])

    positive_count = Txn.sum(:points,
                             :conditions=> ["txn_date >= ? AND txn_date < ?", txn_date, (txn_date + 1.days)],
                             :joins=> " INNER JOIN activities ON activities.id = txns.activity_id AND activities.activity_type = 1")

    negative_count = Txn.sum(:points,
                             :conditions=> ["txn_date >= ? AND txn_date < ?", txn_date, (txn_date + 1.days)],
                             :joins=> " INNER JOIN activities ON activities.id = txns.activity_id AND activities.activity_type = 2")

    positive_count - negative_count
  end

  def self.cumulative_points

    positive_count = Txn.sum(:points,
                             :joins=> " INNER JOIN activities ON activities.id = txns.activity_id AND activities.activity_type = 1")

    negative_count = Txn.sum(:points,
                             :joins=> " INNER JOIN activities ON activities.id = txns.activity_id AND activities.activity_type = 2")

    positive_count - negative_count
  end

  def self.history txn_date
    Txn.all(:conditions=> ["txn_date >= ? AND txn_date < ?", txn_date, (txn_date + 1.days)],
            :joins=> " INNER JOIN activities ON activities.id = txns.activity_id")
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

 def index
   @activities = Activity.all
 end

 def new
  @activity = Activity.new
 end

 def create
    @activity = Activity.new(params[:activity])
    if @activity.save
      redirect_to activities_path
    else
      render 'new'
    end  
 end

 def edit
  @activity = Activity.find(params[:id])
 end

 def update
   @activity = Activity.find(params[:id])
   if @activity.update_attributes(params[:activity])
     redirect_to activities_path
   else
     render 'edit'
   end 
 end

 def destroy
  Activity.find(params[:id]).destroy
  redirect_to activities_path
 end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/txns_controller.rb
class TxnsController < ApplicationController

  def index
    @cumulative_points = Txn.cumulative_points
    if params[:txnDate]
      txn_date = DateTime.strptime(params[:txn][:txn_date], '%m/%d/%Y')
      @txns = Txn.history txn_date
      @total_score = Txn.total_points txn_date
    else
      @txns = Txn.history Date.today
      @total_score = Txn.total_points Date.today
    end
  end

  def new
    @cumulative_points = Txn.cumulative_points
    @total_score = Txn.total_points Date.today
    @activities = Activity.all
  end

  def create
    @txn = Txn.new(params[:txn])
    @txn.txn_date = DateTime.strptime(params[:txn][:txn_date], '%m/%d/%Y')
    @txn.save

    @total_score = Txn.total_points Date.today
    @cumulative_points = Txn.cumulative_points
    respond_to do |format|
      format.js
    end
  end

  def destroy
    Txn.find(params[:id]).destroy
    redirect_to txns_path
  end

end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_activity.html.erb
<div class='activity'> 
  <div class='activityTitle'><%= activity.title %></div>
  <div class='activityPoints'>
    <span class=" <%= activity.activity_type == 1 ? 'PositiveSign': 'NegativeSign' %>">
      <%= activity.activity_type == 1 ? '+': '-' %>
    </span>
    <span><%= activity.points%></span></div>
  <div class='activityEdit'><%= link_to 'Edit', edit_activity_path(activity) %></div>
  <div class='activityDelete'><%= link_to 'Delete', activity, :confirm => 'Are you sure?',:method => :delete %></div>
  <div class="clear"></div>
</div>

app/views/activities/_fields.html.erb
  <div class="fieldRow">
    <div class="label"><%= f.label :title %></div>
    <div class="inputBox"><%= f.text_field :title, :size => 55 %></div>
    <div class="clear"></div>
  </div>
  <div class="fieldRow">
    <div class="label"><%= f.label :points %></div>
    <div class="inputBox"><%= f.text_field :points, :size => 10 %></div>
    <div class="clear"></div>
  </div>
  <div class="fieldRow">
    <div class="label"><%= f.label :activity_type %></div>
    <div class="inputBox"><%= f.text_field :activity_type, :size => 5 %></div>
    <div class="clear"></div>
  </div>

app/views/activities/edit.html.erb
<div class="activityContainer">
  <h1>Edit Activity</h1>

  <%= form_for(@activity) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="fieldRow">
        <div class="label">&nbsp;</div>
        <div class="inputBox"><%= f.submit "Update" %></div>
        <div class="clear"></div>
      </div>
  <% end %>
</div>

app/views/activities/index.html.erb
<div class="activityContainer">
  <h1>Activities</h1>

  <div>
    <% @activities.each do |activity| %>
        <%= render activity %>
    <% end %>
  </div>
  <br/>
  <div>
    <%= link_to 'New Activity', new_activity_path %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="activityContainer">
  <h1> Add Activity </h1>

  <%= form_for(@activity) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="fieldRow">
        <div class="label">&nbsp;</div>
        <div class="inputBox"><%= f.submit "Add Activity" %></div>
        <div class="clear"></div>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Points</title>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="topBar">
  <div class='logo'>
     <span>my Points</span>
   </div>
   <div class="userData">
     <span id="cumulativePoints"><%= @cumulative_points %></span>
   </div>
  <div class="navigation">
    <span><a href="/txns/new">Today</a> </span>&nbsp;
    <span><a href="/txns">History</a></span>&nbsp;
    <span><a href="/activities">Configuration</a></span>
  </div>
   <div class="userImageSection"><img class='userImage' src="/images/amrits.JPG"/></div>
   <div class="clear"></div>
</div>
<div class="container">
  <section class="round">
    <%= yield %>
  </section>
</div>
</body>
</html>

app/views/txns/_fields.html.erb
<script type='text/javascript'>
  $(function (){
    $('#txn_txn_date').datepicker();
   });
</script>

  <div class="field">
    <%= f.label :txn_date %><br />
    <%= f.text_field :txn_date %>
  </div>
  <div class="field">
    <%= f.label :activity_id %><br />
    <%= collection_select(:txn, :activity_id, Activity.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.text_field :points, :size => 10 %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>

app/views/txns/_txn.html.erb
<div class="txn">
  <div class="titleTxn"><%= txn.activity.title %></div>
  <div class="pointsTxn">
    <span class=" <%= txn.activity.activity_type == 1 ? 'PositiveSign' : 'NegativeSign' %>">
      <%= txn.activity.activity_type == 1 ? '+' : '-' %>
    </span>
    <span><%= txn.points %></span></div>
  <div class="deleteTxn"><%= link_to 'Delete', txn, :method => :delete %></div>
  <div class="clear"></div>
</div>

app/views/txns/edit.html.erb
<h1>Edit Action</h1>

<%= form_for(@txn) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/txns/index.html.erb
<input type='hidden' id='txnDate' value="<%= Date.today.strftime('%m/%d/%Y') %>"/>
<div class="txnContainer">
  <!-- DATE AND DAILY SCORE -->
  <div>
    <div class="selectedDate"><%= Date.today.strftime('%A, %B %-d, %Y') %></div>
    <div class="dailyScore" id='dailyScore'><%= @total_score %></div>
    <div class="clear"></div>
  </div>
  <div>
    <% @txns.each do |txn| %>
        <%= render txn %>
    <% end %>
  </div>
  <div class="clear"></div>
</div>

app/views/txns/new.html.erb
<script type="text/javascript">

    var activities = null;
    var selected_activity_index = 0;

    $(function() {
        activities = <%= @activities.to_json.html_safe %>;
        selected_activity_index = parseInt(activities.length / 2);
        renderSelector();
    });

    $(function() {
        $(".selection").live("click", function() {
            clickedID = $(this).attr('activityID');
            currentPositionType = $(this).attr('id').substring(4, 8);
            currentPositionIndex = $(this).attr('id').substring(8);

            if (currentPositionType == 'Prev') {
                for (i = currentPositionIndex; i > 0; i--) {
                    var obj = activities.pop();
                    activities.unshift(obj);
                    renderSelector();
                }
            }
            else {

                for (i = currentPositionIndex; i > 0; i--) {
                    var obj = activities.shift();
                    activities.push(obj);
                }
                renderSelector();
            }

            // renderSelector();
        });
    })

    function activitiesUp() {
        var obj = activities.shift();
        activities.push(obj);
        renderSelector();
    }


    function activitiesDown() {
        var obj = activities.pop();
        activities.unshift(obj);
        renderSelector();
    }

    function activityAdd() {

        var activity_id = $('#itemSelected').attr('activityID');
        var dailyScore = parseInt($('#dailyScore').text());
        var changePoints = parseInt($('#changePoints').text());
        var txn_date = $("#txnDate").val();
        // call ajax to persist
        $.post("/txns", { txn : {txn_date: txn_date, activity_id: activity_id, points: changePoints, comments: '' } });
    }


    function renderSelector() {

        resetSelector();
        setSelected();
        setRemaining();
    }

    function resetSelector() {
        $('#itemSelected').text('');
        $('#itemPrev1').text('');
        $('#itemPrev2').text('');
        $('#itemPrev3').text('');
        $('#itemPrev4').text('');
        $('#itemPrev5').text('');
        $('#itemPrev6').text('');
        $('#itemNext1').text('');
        $('#itemNext2').text('');
        $('#itemNext3').text('');
        $('#itemNext4').text('');
        $('#itemNext5').text('');
        $('#itemNext6').text('');
    }

    function setSelected() {

        // first take care of selected activity
        $('#itemSelected').text(activities[selected_activity_index].activity.title);
        $('#itemSelected').attr('activityID', activities[selected_activity_index].activity.id);
        $('#changePoints').text(activities[selected_activity_index].activity.points);

        if (activities[selected_activity_index].activity.activity_type == 1) {
            $('#activityType').text("+");
            $('#activityType').removeClass("NegativeSign");
            $('#activityType').addClass("PositiveSign");
            // $('#GOButton').removeClass("GONegative");
            // $('#GOButton').addClass("GOPositive");
        }
        else {
            $('#activityType').text("-");
            $('#activityType').removeClass("PositiveSign");
            $('#activityType').addClass("NegativeSign");
            // $('#GOButton').removeClass("GOPositive");
            // $('#GOButton').addClass("GONegative");
        }
    }

    function setRemaining() {

        // set all prior to index
        for (var i = 1; i <= 6; i++) {
            index = selected_activity_index - i;
            if (index >= 0) {
                $('#itemPrev' + i).text(activities[index].activity.title);
                $('#itemPrev' + i).attr('activityID', activities[index].activity.id);
            }
        }

        // set all after the index
        for (var i = 1; i <= 6; i++) {
            index = selected_activity_index + i;
            if (index < activities.length) {
                $('#itemNext' + i).text(activities[index].activity.title);
                $('#itemNext' + i).attr('activityID', activities[index].activity.id);
            }
        }

    }


</script>
<input type='hidden' id='txnDate' value="<%= Date.today.strftime('%m/%d/%Y') %>"/>

<div class="txnContainer">
  <!-- DATE AND DAILY SCORE -->
  <div>
    <div class="selectedDate"><%= Date.today.strftime('%A, %B %-d, %Y') %></div>
    <div class="dailyScore" id='dailyScore'><%= @total_score %></div>
    <div class="clear"></div>
  </div>

  <!-- SELECTIONS AND ACTIONS -->

  <div class="selectionsAndActions">
    <!-- SELECTIONS -->
    <div class="selections">
      <div id='itemPrev6' class="clickable selection"></div>
      <div id='itemPrev5' class="clickable selection"></div>
      <div id='itemPrev4' class="clickable selection"></div>
      <div id='itemPrev3' class="clickable selection"></div>
      <div id='itemPrev2' class="clickable selection"></div>
      <div id='itemPrev1' class="clickable selection"></div>

      <div class="selectedItem">
        <span id="itemSelected"></span>
        <span id="activityType" class="NegativeSign">-</span>
        <span id='changePoints'></span>
      </div>

      <div id='itemNext1' class="clickable selection"></div>
      <div id='itemNext2' class="clickable selection"></div>
      <div id='itemNext3' class="clickable selection"></div>
      <div id='itemNext4' class="clickable selection"></div>
      <div id='itemNext5' class="clickable selection"></div>
      <div id='itemNext6' class="clickable selection"></div>
    </div>

    <!-- ACTIONS -->
    <div class="actions">
      <div>
        <div class="upArrow">
          <img class="clickable directionImage" onclick="activitiesUp();" src='/images/button-up.gif'/>
        </div>
        <div class="goButton">
          <img class="clickable goImage" onclick="activityAdd();" src="/images/go.gif" />
        </div>
        <div class="downArrow">
          <img class="clickable directionImage" onclick="activitiesDown();" src='/images/button-down.gif'/>
        </div>
      </div>
    </div>

    <div class="clear"></div>
  </div>
</div>